x=int(input("Enter the first number :"))
y=int(input("Enter the second number :"))
print("Sum : ",x,"+",y,"=",x+y)
print("diffrence : ",x,"-",y,"=",x-y)
print("Multiplication : ",x,"*",y,"=",x*y)
print("Division : ",x,"/",y,"=",x/y)
print("Reminder : ",x,"%",y,"=",x%y)
